(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DATA={materials:[
{id:'S-001',name:'Ashwagandha KSM-66',min:5000},{id:'S-002',name:'Boswellia serrata',min:4000},{id:'S-003',name:'Rozchodnice růžová',min:3500},{id:'S-004',name:'Kotvičník zemní',min:2500},{id:'S-005',name:'Maca',min:3000}],
boxes:Array.from({length:20},(_,i)=>({id:String(i+1)})),
positions:Array.from({length:4},(_,r)=>Array.from({length:10},(_,c)=>({id:`${String.fromCharCode(65+r)}${c+1}`}))).flat(),
packs:[{id:'P-2026-001',material:'S-001',lot:'AK66-260801',expiry:'08/27',qty:2400,box:'1',position:'A1',state:'nový'},{id:'P-2026-002',material:'S-001',lot:'AK66-260812',expiry:'08/27',qty:1800,box:'2',position:'A2',state:'otevřený'},{id:'P-2026-003',material:'S-002',lot:'BS-260802',expiry:'08/27',qty:4100,box:'3',position:'A3',state:'nový'},{id:'P-2026-004',material:'S-003',lot:'RR-260805',expiry:'08/27',qty:3200,box:'4',position:'B1',state:'nový'},{id:'P-2026-005',material:'S-004',lot:'KT-260808',expiry:'08/27',qty:2100,box:'5',position:'B2',state:'otevřený'},{id:'P-2026-006',material:'S-005',lot:'MA-260810',expiry:'08/27',qty:2900,box:'6',position:'B3',state:'nový'},{id:'P-2026-007',material:'S-002',lot:'BS-260818',expiry:'08/27',qty:2200,box:'7',position:'C1',state:'nový'}],
movements:[{id:'M-001',date:'30. 8. 2026 08:50',type:'Příjem',pack:'P-2026-007',qty:2200,from:'Příjem',to:'C1'},{id:'M-002',date:'30. 8. 2026 08:10',type:'Výdej',pack:'P-2026-002',qty:-300,from:'A2',to:'Výdej'},{id:'M-003',date:'29. 8. 2026 16:31',type:'Přesun',pack:'P-2026-005',qty:0,from:'A4',to:'B2'},{id:'M-004',date:'29. 8. 2026 13:05',type:'Výdej',pack:'P-2026-001',qty:-400,from:'A1',to:'Výdej'}]};
const PAGES=[{id:'dashboard',label:'Přehled'},{id:'inventory',label:'Zásoby'},{id:'warehouse',label:'Pozice'},{id:'movements',label:'Pohyby'},{id:'materials',label:'Suroviny'},{id:'counts',label:'Inventura'}];
const state={page:localStorage.getItem('mp12-page')||'inventory',previous:null,direction:1,q:'',theme:localStorage.getItem('mp12-theme')||'dark'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mat=id=>DATA.materials.find(x=>x.id===id); const fmt=n=>new Intl.NumberFormat('cs-CZ',{maximumFractionDigits:2}).format(Number(n)||0);
function activePacks(){return DATA.packs.filter(x=>x.qty>0)} function totalStock(){return activePacks().reduce((a,x)=>a+x.qty,0)}
function summary(){const a=activePacks();$('#summary').innerHTML=[['Pytle',a.length,'aktivní'],['Sklad',fmt(totalStock()),'g celkem'],['Boxy',new Set(a.map(x=>x.box)).size,'obsazené'],['Pozice',new Set(a.map(x=>x.position)).size,'použité']].map(x=>`<div class="metric"><small>${x[0]}</small><strong>${x[1]}</strong><span>${x[2]}</span></div>`).join('')}
function pageTabs(){ $('#pageTabs').innerHTML=PAGES.map((p,i)=>`<button class="page-tab ${p.id===state.page?'active':''}" data-page="${p.id}">${esc(p.label)}</button>`).join(''); $$('.page-tab').forEach(b=>b.onclick=()=>switchPage(b.dataset.page)); }
function table(headers,rows){return `<div class="table-card"><div class="table-head"><small>${rows.length} ${rows.length===1?'řádek':'řádků'}</small><div class="table-actions"><button class="btn" data-refresh>Obnovit</button></div></div><div class="table-scroll"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.join(''):`<tr><td colspan="${headers.length}" class="empty">Nic nenalezeno</td></tr>`}</tbody></table></div></div>`}
function inventory(){let rows=activePacks(); if(state.q)rows=rows.filter(p=>`${p.id} ${p.lot} ${p.position} ${p.box} ${mat(p.material)?.name}`.toLocaleLowerCase('cs-CZ').includes(state.q)); return table(['ID pytle','Surovina','Šarže','Expirace','Box','Pozice','Aktuální hmotnost','Stav',''],rows.map(p=>`<tr><td class="mono">${p.id}</td><td>${esc(mat(p.material)?.name||p.material)}</td><td class="mono">${esc(p.lot)}</td><td>${esc(p.expiry)}</td><td>${esc(p.box)}</td><td><span class="pill">${esc(p.position)}</span></td><td class="num">${fmt(p.qty)} g</td><td><span class="pill">${esc(p.state)}</span></td><td class="row-actions"><button class="row-btn" data-detail="${p.id}">Detail</button><button class="row-btn" data-move="${p.id}">Přesun</button></td></tr>`));}
function warehouse(){const groups={}; activePacks().forEach(p=>(groups[p.position]??=[]).push(p)); const rows=Object.entries(groups).sort().map(([pos,ps])=>`<tr><td><span class="pill">${pos}</span></td><td>${ps.map(p=>p.box).join(', ')}</td><td>${ps.map(p=>esc(mat(p.material)?.name||p.material)).join(' · ')}</td><td class="num">${fmt(ps.reduce((a,p)=>a+p.qty,0))} g</td><td>${ps.length}</td></tr>`); return table(['Pozice','Boxy','Suroviny','Hmotnost','Pytle'],rows)}
function movements(){let rows=DATA.movements; if(state.q)rows=rows.filter(m=>`${m.id} ${m.type} ${m.pack} ${m.from} ${m.to}`.toLocaleLowerCase('cs-CZ').includes(state.q));return table(['ID','Datum','Typ','Pytel','Množství','Odkud','Kam'],rows.map(m=>`<tr><td class="mono">${m.id}</td><td>${m.date}</td><td><span class="pill">${m.type}</span></td><td class="mono">${m.pack}</td><td class="num">${m.qty?fmt(m.qty)+' g':'—'}</td><td>${m.from}</td><td>${m.to}</td></tr>`))}
function materials(){let rows=DATA.materials; if(state.q)rows=rows.filter(m=>`${m.id} ${m.name}`.toLocaleLowerCase('cs-CZ').includes(state.q)); return table(['ID','Surovina','Pytle','Hmotnost','Minimum'],rows.map(m=>{const ps=activePacks().filter(p=>p.material===m.id);return `<tr><td class="mono">${m.id}</td><td><strong>${esc(m.name)}</strong></td><td>${ps.length}</td><td class="num">${fmt(ps.reduce((a,p)=>a+p.qty,0))} g</td><td class="num">${fmt(m.min)} g</td></tr>`}))}
function counts(){return table(['Inventura','Stav','Položek','Akce'],[`<tr><td><strong>Průběžná inventura</strong></td><td><span class="pill">Připravena</span></td><td>0</td><td><button class="row-btn" data-startcount>Začít</button></td></tr>`])}
function dashboard(){return `<div class="dashboard"><section class="panel"><h2>Rychlý přehled</h2><div class="stats-grid"><div class="mini-stat"><small>Pytle</small><strong>${activePacks().length}</strong></div><div class="mini-stat"><small>Hmotnost</small><strong>${fmt(totalStock())} g</strong></div><div class="mini-stat"><small>Pohyby</small><strong>${DATA.movements.length}</strong></div></div><h2>Poslední pohyby</h2><div class="quick">${DATA.movements.slice(0,4).map(m=>`<button data-page="movements"><span>${m.type}</span><strong>${m.pack}</strong><span>${m.to}</span></button>`).join('')}</div></section><section class="panel"><h2>Stránky</h2><div class="quick">${PAGES.filter(p=>p.id!=='dashboard').map(p=>`<button data-page="${p.id}"><strong>${p.label}</strong><span>→</span></button>`).join('')}</div></section></div>`}
function contentFor(id){return id==='dashboard'?dashboard():id==='inventory'?inventory():id==='warehouse'?warehouse():id==='movements'?movements():id==='materials'?materials():counts()}
function includePages(page=state.page){const viewport=$('#pageViewport');const old=viewport.querySelector('.page-layer.active');const layer=document.createElement('section');layer.className='page-layer';layer.innerHTML=contentFor(page); viewport.appendChild(layer); requestAnimationFrame(()=>{if(old){old.classList.remove('active');old.classList.add(state.direction>0?'before':'behind');setTimeout(()=>old.remove(),240)}layer.classList.add('active');}); if(!old)layer.classList.add('instant','active');}
function switchPage(page){if(page===state.page)return;const a=PAGES.findIndex(p=>p.id===state.page),b=PAGES.findIndex(p=>p.id===page);state.direction=b>a?1:-1;state.previous=state.page;state.page=page;localStorage.setItem('mp12-page',page);pageTabs();$('#pageTitle').textContent=PAGES.find(p=>p.id===page)?.label||page;$('#pageKicker').textContent='Pages';includePages(page);}
function openDialog(title,fields,onSave){$('#dialogTitle').textContent=title;$('#formFields').innerHTML=`<div class="dialog-fields">${fields}</div>`;$('#dialog').showModal();$('#form').onsubmit=e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();onSave(new FormData($('#form')));$('#dialog').close();}}
function receive(){openDialog('Příjem zásoby',`<label>ID pytle<input name="id" value="P-2026-008" required></label><label>Šarže<input name="lot" required></label><label>Expirace (MM/YY)<input name="expiry" placeholder="08/27" required></label><label>Hmotnost (g)<input name="qty" type="number" min="0" step="0.01" value="1000" required></label><label>Box<input name="box" value="8" required></label><label>Pozice<input name="position" value="C2" required></label>`,f=>{DATA.packs.unshift({id:f.get('id'),material:'S-001',lot:f.get('lot'),expiry:f.get('expiry'),qty:+f.get('qty'),box:String(f.get('box')),position:f.get('position'),state:'nový'});render();});}
function move(id){const p=DATA.packs.find(x=>x.id===id);if(!p)return;openDialog('Přesun pytle',`<label>Pytel<input value="${esc(p.id)}" disabled></label><label>Nová pozice<input name="position" value="${esc(p.position)}" required></label>`,f=>{const from=p.position;p.position=f.get('position');DATA.movements.unshift({id:`M-${String(DATA.movements.length+1).padStart(3,'0')}`,date:new Date().toLocaleString('cs-CZ'),type:'Přesun',pack:p.id,qty:0,from,to:p.position});render();});}
function detail(id){const p=DATA.packs.find(x=>x.id===id);if(!p)return;openDialog(p.id,`<label>Surovina<input value="${esc(mat(p.material)?.name||p.material)}" disabled></label><label>Šarže<input value="${esc(p.lot)}" disabled></label><label>Hmotnost<input value="${fmt(p.qty)} g" disabled></label><label>Pozice<input value="${esc(p.position)}" disabled></label>`,()=>{});}
function render(){document.documentElement.dataset.theme=state.theme;summary();pageTabs();$('#pageTitle').textContent=PAGES.find(p=>p.id===state.page)?.label||'';$('#search').value=state.q;$('#pageViewport').querySelectorAll('.page-layer').forEach(x=>x.remove());includePages(state.page);}
$('#search').oninput=e=>{state.q=e.target.value;const active=$('#pageViewport .page-layer.active');if(active){active.innerHTML=contentFor(state.page);}};
$('#themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';localStorage.setItem('mp12-theme',state.theme);render();};
$('#refreshBtn').onclick=()=>render();$('#addBtn').onclick=receive;
$('#pageViewport').addEventListener('click',e=>{const page=e.target.closest('[data-page]');if(page){switchPage(page.dataset.page);return}const m=e.target.closest('[data-move]');if(m)move(m.dataset.move);const d=e.target.closest('[data-detail]');if(d)detail(d.dataset.detail);const c=e.target.closest('[data-startcount]');if(c)openDialog('Inventura','<div class="dialog-fields"><p>Zahájit novou inventuru skladu?</p></div>',()=>{});});
render();
})();