import './styles.css'

const DB_KEY = 'mp12-inventory-v3'
const THEME_KEY = 'mp12-theme'
const CSV_COLUMNS = ['id','material','lot','expiry','box','position','qty','packState']

const seed = {
  materials: [
    { id:'S-001', name:'Hroznový extrakt', min:5000 },
    { id:'S-002', name:'MagChel Magnesium bisglycinate', min:4000 },
    { id:'S-003', name:'Heřmánkový extrakt', min:2500 },
    { id:'S-004', name:'Mátový extrakt', min:2500 },
    { id:'S-005', name:'Ashwagandha extrakt', min:3000 }
  ],
  boxes: Array.from({length:12}, (_,i) => ({id:String(i+1)})),
  positions: Array.from({length:40}, (_,i) => ({id:`${String.fromCharCode(65 + Math.floor(i/10))}${i%10+1}`})),
  packs: [
    {id:'P-2026-001',material:'S-001',lot:'AK66-260801',expiry:'08/27',box:'1',position:'A1',qty:2400,packState:'nový'},
    {id:'P-2026-002',material:'S-001',lot:'AK66-260812',expiry:'08/27',box:'2',position:'A2',qty:1800,packState:'otevřený'},
    {id:'P-2026-003',material:'S-002',lot:'BS-260802',expiry:'08/27',box:'3',position:'A3',qty:4100,packState:'nový'},
    {id:'P-2026-004',material:'S-003',lot:'RR-260805',expiry:'08/27',box:'4',position:'B1',qty:3200,packState:'nový'},
    {id:'P-2026-005',material:'S-004',lot:'KT-260808',expiry:'08/27',box:'5',position:'B2',qty:2100,packState:'otevřený'},
    {id:'P-2026-006',material:'S-005',lot:'MA-260810',expiry:'08/27',box:'6',position:'B3',qty:2900,packState:'nový'},
    {id:'P-2026-007',material:'S-002',lot:'BS-260818',expiry:'09/27',box:'7',position:'C1',qty:2200,packState:'nový'}
  ],
  movements: [
    {id:'M-001',date:'2026-08-30T08:50:00',type:'Příjem',pack:'P-2026-007',qty:2200,from:'Příjem',to:'C1',reason:'Příjem zásoby'},
    {id:'M-002',date:'2026-08-30T08:10:00',type:'Výdej',pack:'P-2026-002',qty:-300,from:'A2',to:'Výdej',reason:'Výdej'},
    {id:'M-003',date:'2026-08-29T16:31:00',type:'Přesun',pack:'P-2026-005',qty:0,from:'A4',to:'B2',reason:'Změna pozice'}
  ],
  counts: [],
  meta: { nextPack:8, nextMovement:4, nextMaterial:6, nextCount:1 }
}

const state = { page:'inventory', q:'', sort:{key:'material',dir:'asc'}, compact:false, theme:localStorage.getItem(THEME_KEY)||'dark' }
let db = loadDb()

function clone(x){return JSON.parse(JSON.stringify(x))}
function loadDb(){try{const raw=JSON.parse(localStorage.getItem(DB_KEY)||'null');return raw?normalize(raw):clone(seed)}catch{return clone(seed)}}
function saveDb(){localStorage.setItem(DB_KEY,JSON.stringify(db))}
function normalize(data){const d={...clone(seed),...data};d.materials=Array.isArray(d.materials)?d.materials:[];d.boxes=Array.isArray(d.boxes)?d.boxes.map(x=>({id:String(x.id).replace(/^B-/i,'')})):[];d.positions=Array.isArray(d.positions)?d.positions:[];d.packs=Array.isArray(d.packs)?d.packs.map(p=>({...p,id:String(p.id),material:String(p.material),lot:String(p.lot||''),expiry:normExpiry(p.expiry),box:String(p.box||''),position:String(p.position||''),qty:Math.max(0,Number(p.qty)||0),packState:p.packState==='otevřený'?'otevřený':'nový'})):[];d.movements=Array.isArray(d.movements)?d.movements:[];d.counts=Array.isArray(d.counts)?d.counts:[];d.meta={...clone(seed.meta),...(d.meta||{})};return d}
function normExpiry(v){const m=String(v??'').trim().replace(/\./g,'/').match(/^(\d{1,2})\/(\d{2})$/);return m?`${m[1].padStart(2,'0')}/${m[2]}`:String(v||'')}
function esc(v){return String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function fmt(n){return new Intl.NumberFormat('cs-CZ',{maximumFractionDigits:2}).format(Number(n)||0)}
function material(id){return db.materials.find(x=>x.id===id)}
function pack(id){return db.packs.find(x=>x.id===id)}
function nextId(kind,prefix){const key=`next${kind}`;const n=Number(db.meta[key]||1);db.meta[key]=n+1;return `${prefix}${String(n).padStart(3,'0')}`}
function expRank(v){const m=String(v).match(/^(\d{2})\/(\d{2})$/);return m?(2000+Number(m[2]))*12+Number(m[1]):Number.MAX_SAFE_INTEGER}
function expState(v){const d=expRank(v);if(!Number.isFinite(d)||d===Number.MAX_SAFE_INTEGER)return'neznámá';const now=new Date(),cur=now.getFullYear()*12+now.getMonth()+1,diff=d-cur;return diff<0?'po expiraci':diff<=2?'brzy expiruje':'OK'}
function activePacks(){return db.packs.filter(p=>p.qty>0)}
function stock(){return activePacks().reduce((a,p)=>a+p.qty,0)}
function pageMeta(){return{inventory:{title:'Zásoby',desc:'Pytle, šarže, expirace, boxy a pozice.'},warehouse:{title:'Pozice',desc:'Rychlý pohled na fyzické uložení skladu.'},movements:{title:'Pohyby',desc:'Audit příjmů, výdejů a přesunů.'},materials:{title:'Suroviny',desc:'Neměnný katalog názvů a ID surovin.'},counts:{title:'Inventury',desc:'Evidence inventurních kontrol.'}}[state.page]}

const app=document.querySelector('#app')
app.innerHTML=`<div class="app-shell"><aside class="sidebar" id="sidebar"><div class="brand"><div class="brand-mark">M</div><div><b>MP12</b><span>INVENTORY</span></div></div><button class="new-btn" id="newBtn">＋ Nový záznam</button><div class="nav-label">PAGES</div><nav id="nav"></nav><div class="sidebar-foot"><button class="ghost-btn" id="importBtn">↑ Import CSV</button><button class="ghost-btn" id="exportBtn">↓ Export CSV</button><button class="ghost-btn" id="themeBtn">◐ Motiv</button><small>GitHub Pages · local DB</small></div></aside><main class="main"><header class="mobile-bar"><button id="menuBtn" class="icon-btn">☰</button><b>MP12</b></header><div class="stage" id="stage"></div></main></div><input type="file" id="csvFile" accept=".csv,text/csv" hidden/><div id="modalRoot"></div><div id="toastRoot" class="toast-root"></div>`

function renderNav(){const items=[['inventory','▤','Zásoby'],['warehouse','⌗','Pozice'],['movements','↕','Pohyby'],['materials','◇','Suroviny'],['counts','◫','Inventury']];document.querySelector('#nav').innerHTML=items.map(([id,icon,label])=>`<button class="nav-item ${state.page===id?'active':''}" data-page="${id}"><span>${icon}</span>${label}</button>`).join('')}
function switchPage(next){if(next===state.page)return;const old=document.querySelector('.page-layer.current');state.page=next;const layer=buildPageLayer();layer.classList.add('enter');document.querySelector('#stage').appendChild(layer);requestAnimationFrame(()=>{layer.classList.remove('enter');if(old){old.classList.remove('current');old.classList.add('exit');setTimeout(()=>old.remove(),240)}});renderNav();closeSidebar()}
function buildPageLayer(){const meta=pageMeta(),layer=document.createElement('section');layer.className='page-layer current';layer.innerHTML=`<div class="page-head"><div><div class="eyebrow">PAGES / ${state.page.toUpperCase()}</div><h1>${meta.title}</h1><p>${meta.desc}</p></div><div class="head-actions"><button class="btn" id="refreshBtn">Obnovit</button><button class="btn primary" id="headAction">＋ Přidat</button></div></div><div class="page-content">${renderPageContent()}</div>`;layer.querySelector('#refreshBtn').onclick=()=>renderPage();layer.querySelector('#headAction').onclick=()=>newRecord();return layer}
function renderPage(){const stage=document.querySelector('#stage');stage.innerHTML='';stage.appendChild(buildPageLayer())}
function renderPageContent(){if(state.page==='inventory')return inventoryPage();if(state.page==='warehouse')return warehousePage();if(state.page==='movements')return movementsPage();if(state.page==='materials')return materialsPage();return countsPage()}
function tableToolbar(extra=''){return`<div class="table-tools"><label class="search"><span>⌕</span><input id="q" value="${esc(state.q)}" placeholder="Hledat…"/></label><div class="tool-group">${extra}<button class="btn small" id="compactBtn">${state.compact?'Standard':'Kompaktní'}</button></div></div>`}
function inventoryRows(){const q=state.q.trim().toLocaleLowerCase('cs-CZ');const rows=activePacks().filter(p=>`${p.id} ${material(p.material)?.name||''} ${p.lot} ${p.expiry} ${p.box} ${p.position} ${p.packState}`.toLocaleLowerCase('cs-CZ').includes(q));const key=state.sort.key,dir=state.sort.dir;rows.sort((a,b)=>{let x=key==='material'?material(a.material)?.name||'':key==='qty'?a.qty:key==='expiry'?expRank(a.expiry):a[key]||'';let y=key==='material'?material(b.material)?.name||'':key==='qty'?b.qty:key==='expiry'?expRank(b.expiry):b[key]||'';const r=x>y?1:x<y?-1:0;return dir==='asc'?r:-r});return rows}
function th(key,label){return`<th><button class="th-btn" data-sort="${key}">${label}<span>↕</span></button></th>`}
function inventoryPage(){const rows=inventoryRows();return`${tableToolbar('<button class="btn small" id="receiveBtn">＋ Příjem</button><button class="btn small" id="moveBtn">↕ Přesun</button><button class="btn small" id="issueBtn">− Výdej</button>')}<div class="table-card"><table><thead><tr>${th('id','ID pytle')}${th('material','Surovina')}${th('lot','Šarže')}${th('expiry','Expirace')}${th('box','Box')}${th('position','Pozice')}${th('qty','Hmotnost (g)')}<th>Stav</th><th></th></tr></thead><tbody>${rows.length?rows.map(p=>`<tr><td class="mono"><b>${esc(p.id)}</b></td><td>${esc(material(p.material)?.name||p.material)}</td><td class="mono">${esc(p.lot)}</td><td class="mono"><span class="expiry ${expState(p.expiry)!=='OK'?'warn':''}">${esc(p.expiry)}</span></td><td class="mono">${esc(p.box)}</td><td><span class="chip">${esc(p.position)}</span></td><td class="mono"><b>${fmt(p.qty)}</b></td><td><span class="badge ${p.packState==='otevřený'?'open':'new'}">${esc(p.packState)}</span></td><td><button class="row-action" data-action="menu" data-id="${esc(p.id)}">•••</button></td></tr>`).join(''):`<tr><td colspan="9" class="empty">Žádné záznamy.</td></tr>`}</tbody></table></div>`}
function warehousePage(){return`<div class="warehouse-card"><div class="warehouse-grid">${db.positions.map(pos=>{const items=activePacks().filter(p=>p.position===pos.id),qty=items.reduce((a,p)=>a+p.qty,0);return`<button class="slot ${items.length?'busy':''}" data-slot="${pos.id}"><b>${pos.id}</b><span>${items.length?`${items.length} pytle`:'volná'}</span>${items.length?`<small>${fmt(qty)} g</small>`:''}</button>`}).join('')}</div></div>`}
function movementsPage(){const q=state.q.toLowerCase(),rows=db.movements.filter(m=>`${m.id} ${m.type} ${m.pack} ${m.from} ${m.to} ${m.reason}`.toLowerCase().includes(q)).sort((a,b)=>b.date.localeCompare(a.date));return`${tableToolbar()}<div class="table-card"><table><thead><tr><th>ID</th><th>Čas</th><th>Typ</th><th>Pytel</th><th>Trasa</th><th>Množství</th><th>Důvod</th></tr></thead><tbody>${rows.length?rows.map(m=>`<tr><td class="mono">${esc(m.id)}</td><td>${new Date(m.date).toLocaleString('cs-CZ',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</td><td><span class="badge ${m.type==='Příjem'?'new':m.type==='Výdej'?'open':''}">${esc(m.type)}</span></td><td class="mono">${esc(m.pack)}</td><td>${esc(m.from)} → ${esc(m.to)}</td><td class="mono">${m.qty?`${m.qty>0?'+':''}${fmt(m.qty)} g`:'—'}</td><td>${esc(m.reason)}</td></tr>`).join(''):`<tr><td colspan="7" class="empty">Žádné pohyby.</td></tr>`}</tbody></table></div>`}
function materialsPage(){const q=state.q.toLowerCase(),rows=db.materials.filter(m=>`${m.id} ${m.name}`.toLowerCase().includes(q));return`${tableToolbar('<button class="btn small" id="newMaterialBtn">＋ Surovina</button>')}<div class="table-card"><table><thead><tr><th>ID</th><th>Název</th><th>Minimum (g)</th><th>Aktuální zásoba</th><th></th></tr></thead><tbody>${rows.map(m=>{const qty=activePacks().filter(p=>p.material===m.id).reduce((a,p)=>a+p.qty,0);return`<tr><td class="mono"><b>${esc(m.id)}</b></td><td>${esc(m.name)}</td><td class="mono">${fmt(m.min)}</td><td class="mono">${fmt(qty)} g</td><td><button class="row-action" data-action="material-edit" data-id="${m.id}">Upravit</button></td></tr>`}).join('')}</tbody></table></div>`}
function countsPage(){return`${tableToolbar('<button class="btn small" id="newCountBtn">＋ Inventura</button>')}<div class="table-card"><table><thead><tr><th>ID</th><th>Vytvořeno</th><th>Položek</th><th>Stav</th></tr></thead><tbody>${db.counts.length?db.counts.slice().reverse().map(c=>`<tr><td class="mono">${c.id}</td><td>${new Date(c.createdAt).toLocaleString('cs-CZ')}</td><td>${c.items.length}</td><td><span class="badge">${c.status==='OPEN'?'Otevřená':'Uzavřená'}</span></td></tr>`).join(''):`<tr><td colspan="4" class="empty">Zatím není založená žádná inventura.</td></tr>`}</tbody></table></div>`}
function render(){document.documentElement.dataset.theme=state.theme;document.body.classList.toggle('compact',state.compact);renderNav();renderPage()}
function toast(msg){const n=document.createElement('div');n.className='toast';n.textContent=msg;document.querySelector('#toastRoot').appendChild(n);setTimeout(()=>n.remove(),2200)}
function closeSidebar(){document.querySelector('#sidebar').classList.remove('open')}
function openModal(html,onSubmit){const root=document.querySelector('#modalRoot');root.innerHTML=`<div class="modal-backdrop"><form class="modal-card" id="modalForm"><div class="modal-head"><div class="eyebrow">MP12</div><button type="button" class="icon-btn" data-close>×</button></div>${html}<div class="modal-actions"><button type="button" class="btn" data-close>Zrušit</button><button class="btn primary">Uložit</button></div></form></div>`;root.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>root.innerHTML='');root.querySelector('#modalForm').onsubmit=e=>{e.preventDefault();if(onSubmit(new FormData(e.currentTarget))!==false)root.innerHTML='' }}
function newRecord(){if(state.page==='inventory')return receiveModal();if(state.page==='materials')return materialModal();if(state.page==='counts')return startCount()}
function receiveModal(){openModal(`<h2>Příjem zásoby</h2><div class="form-grid"><label>Surovina<select name="material">${db.materials.map(m=>`<option value="${m.id}">${esc(m.name)}</option>`).join('')}</select></label><label>Šarže<input name="lot" required placeholder="např. 42/26/14"></label><label>Expirace <small>mm/yy</small><input name="expiry" required placeholder="01/28" pattern="\\d{2}/\\d{2}"></label><label>Hmotnost (g)<input name="qty" required type="number" step="0.01" min="0.01"></label><label>Box<select name="box">${db.boxes.map(b=>`<option value="${b.id}">${b.id}</option>`).join('')}</select></label><label>Pozice<select name="position">${db.positions.map(p=>`<option value="${p.id}">${p.id}</option>`).join('')}</select></label><label>Stav<select name="packState"><option>nový</option><option>otevřený</option></select></label></div>`,f=>{const qty=Number(f.get('qty')),expiry=normExpiry(f.get('expiry'));if(!/^\d{2}\/\d{2}$/.test(expiry)||qty<=0){toast('Zkontroluj expiraci a hmotnost.');return false}const id=nextId('Pack','P-2026-');db.packs.push({id,material:String(f.get('material')),lot:String(f.get('lot')).trim(),expiry,box:String(f.get('box')),position:String(f.get('position')),qty,packState:String(f.get('packState'))});db.movements.push({id:nextId('Movement','M-'),date:new Date().toISOString(),type:'Příjem',pack:id,qty,from:'Příjem',to:String(f.get('position')),reason:'Příjem zásoby'});saveDb();render();toast(`${id} přijat.`)})}
function issueModal(id){const p=pack(id);if(!p)return;openModal(`<h2>Výdej · ${esc(id)}</h2><p class="modal-info">Na skladě: <b>${fmt(p.qty)} g</b></p><label>Množství (g)<input name="qty" type="number" step="0.01" min="0.01" max="${p.qty}" required></label><label>Důvod<input name="reason" value="Výdej"></label>`,f=>{const qty=Number(f.get('qty'));if(qty<=0||qty>p.qty){toast('Neplatné množství.');return false}p.qty-=qty;p.packState='otevřený';db.movements.push({id:nextId('Movement','M-'),date:new Date().toISOString(),type:'Výdej',pack:p.id,qty:-qty,from:p.position,to:'Výdej',reason:String(f.get('reason')||'Výdej')});saveDb();render();toast(`Vydáno ${fmt(qty)} g.`)})}
function moveModal(id){const p=pack(id);if(!p)return;openModal(`<h2>Přesun · ${esc(id)}</h2><label>Pozice<select name="position">${db.positions.map(x=>`<option ${x.id===p.position?'selected':''}>${x.id}</option>`).join('')}</select></label><label>Box<select name="box">${db.boxes.map(x=>`<option ${x.id===p.box?'selected':''}>${x.id}</option>`).join('')}</select></label><label>Důvod<input name="reason" value="Změna pozice"></label>`,f=>{const from=p.position;p.position=String(f.get('position'));p.box=String(f.get('box'));db.movements.push({id:nextId('Movement','M-'),date:new Date().toISOString(),type:'Přesun',pack:p.id,qty:0,from,to:p.position,reason:String(f.get('reason')||'Přesun')});saveDb();render();toast(`${p.id} přesunut.`)})}
function materialModal(id=''){const m=id?material(id):null;openModal(`<h2>${m?'Upravit':'Nová'} surovina</h2><label>Název<input name="name" required value="${esc(m?.name||'')}"></label><label>Minimum (g)<input name="min" type="number" min="0" step="0.01" value="${m?.min||0}"></label>`,f=>{const name=String(f.get('name')).trim();if(!name)return false;if(m)Object.assign(m,{name,min:Number(f.get('min'))||0});else db.materials.push({id:nextId('Material','S-'),name,min:Number(f.get('min'))||0});saveDb();render();toast('Surovina uložena.')})}
function startCount(){const id=nextId('Count','IC-');db.counts.push({id,createdAt:new Date().toISOString(),status:'OPEN',items:activePacks().map(p=>({pack:p.id,system:p.qty,actual:p.qty,position:p.position}))});saveDb();render();toast(`Inventura ${id} založena.`)}
function detailMenu(id){const p=pack(id);if(!p)return;openModal(`<h2>${esc(p.id)}</h2><div class="detail-grid"><div><span>Surovina</span><b>${esc(material(p.material)?.name||p.material)}</b></div><div><span>Šarže</span><b>${esc(p.lot)}</b></div><div><span>Expirace</span><b>${esc(p.expiry)}</b></div><div><span>Hmotnost</span><b>${fmt(p.qty)} g</b></div><div><span>Box</span><b>${esc(p.box)}</b></div><div><span>Pozice</span><b>${esc(p.position)}</b></div><div><span>Stav</span><b>${esc(p.packState)}</b></div><div><span>Expirace stav</span><b>${expState(p.expiry)}</b></div></div><div class="quick-actions"><button type="button" class="btn" data-detail="move">Přesun</button><button type="button" class="btn primary" data-detail="issue">Výdej</button></div>`,()=>false);const root=document.querySelector('#modalRoot');root.querySelector('[data-detail="move"]').onclick=()=>{root.innerHTML='';moveModal(id)};root.querySelector('[data-detail="issue"]').onclick=()=>{root.innerHTML='';issueModal(id)}}
function csvEscape(v){const s=String(v??'');return /[",\n;]/.test(s)?`"${s.replaceAll('"','""')}"`:s}
function exportCsv(){const rows=[CSV_COLUMNS.join(';'),...db.packs.map(p=>CSV_COLUMNS.map(k=>csvEscape(k==='material'?(material(p.material)?.name||p.material):p[k])).join(';'))];const blob=new Blob(['\ufeff'+rows.join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`mp12-sklad-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function parseCsv(text){const rows=[];let row=[],cell='',quote=false;const input=text.replace(/^\uFEFF/,'');for(let i=0;i<input.length;i++){const c=input[i],n=input[i+1];if(c==='"'&&quote&&n==='"'){cell+='"';i++;continue}if(c==='"'){quote=!quote;continue}if(c===';'&&!quote){row.push(cell);cell='';continue}if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&n==='\n')i++;row.push(cell);rows.push(row);row=[];cell='';continue}cell+=c}if(cell.length||row.length){row.push(cell);rows.push(row)}return rows.filter(r=>r.some(x=>x!==''))}
function importCsv(text){const rows=parseCsv(text);if(rows.length<2)return;const head=rows.shift().map(x=>x.trim()),ix=k=>head.findIndex(x=>x===k),materialByName=new Map(db.materials.map(m=>[m.name,m.id])),imported=[];for(const r of rows){const matValue=r[ix('material')]??'';let mid=materialByName.get(matValue)||matValue;if(!db.materials.some(m=>m.id===mid)){const newId=nextId('Material','S-');db.materials.push({id:newId,name:matValue||newId,min:0});materialByName.set(matValue||newId,newId);mid=newId}imported.push({id:r[ix('id')]||nextId('Pack','P-2026-'),material:mid,lot:r[ix('lot')]||'IMPORT',expiry:normExpiry(r[ix('expiry')]),box:String(r[ix('box')]||'1').replace(/^B-/i,''),position:r[ix('position')]||'A1',qty:Number(String(r[ix('qty')]||'0').replace(',','.'))||0,packState:r[ix('packState')]==='otevřený'?'otevřený':'nový'})}db.packs=imported;saveDb();render();toast(`Importováno ${imported.length} řádků.`)}

app.addEventListener('click',e=>{const nav=e.target.closest('[data-page]');if(nav){switchPage(nav.dataset.page);return}if(e.target.closest('#newBtn')){newRecord();return}if(e.target.closest('#exportBtn')){exportCsv();return}if(e.target.closest('#importBtn')){document.querySelector('#csvFile').click();return}if(e.target.closest('#themeBtn')){state.theme=state.theme==='dark'?'light':'dark';localStorage.setItem(THEME_KEY,state.theme);render();return}if(e.target.closest('#menuBtn')){document.querySelector('#sidebar').classList.toggle('open');return}if(e.target.closest('#compactBtn')){state.compact=!state.compact;render();return}const sort=e.target.closest('[data-sort]');if(sort){const key=sort.dataset.sort;if(state.sort.key===key)state.sort.dir=state.sort.dir==='asc'?'desc':'asc';else state.sort={key,dir:'asc'};render();return}if(e.target.closest('#receiveBtn')){receiveModal();return}if(e.target.closest('#issueBtn')){const p=activePacks()[0];if(p)issueModal(p.id);return}if(e.target.closest('#moveBtn')){const p=activePacks()[0];if(p)moveModal(p.id);return}const rowAction=e.target.closest('[data-action="menu"]');if(rowAction){detailMenu(rowAction.dataset.id);return}const slot=e.target.closest('[data-slot]');if(slot){const items=activePacks().filter(p=>p.position===slot.dataset.slot);if(items[0])detailMenu(items[0].id);else toast(`${slot.dataset.slot} je volná.`);return}if(e.target.closest('#newMaterialBtn')){materialModal();return}if(e.target.closest('#newCountBtn')){startCount();return}const me=e.target.closest('[data-action="material-edit"]');if(me){materialModal(me.dataset.id);return}const root=e.target.closest('.page-layer');if(root){const q=root.querySelector('#q');if(q&&e.target===q)return}})
document.addEventListener('input',e=>{if(e.target.id==='q'){state.q=e.target.value;const pos=e.target.selectionStart;const active=document.querySelector('.page-layer.current');if(active){const scroll=active.scrollTop;active.querySelector('.page-content').innerHTML=renderPageContent();const q=active.querySelector('#q');if(q){q.focus();q.setSelectionRange(pos,pos)}active.scrollTop=scroll}}})
document.querySelector('#csvFile').addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>importCsv(String(reader.result));reader.readAsText(file,'utf-8');e.target.value=''})
render()
