import './styles.css'

const DB_KEY='mp12-inventory-v4'
const THEME_KEY='mp12-theme'
const CSV=['id','material','lot','expiry','box','position','qty','packState']
const PAGES={inventory:['Zásoby','Pytle, šarže, expirace, boxy a pozice.'],warehouse:['Pozice','Přehled fyzického uložení A1–D10.'],movements:['Pohyby','Audit příjmů, výdejů a přesunů.'],materials:['Suroviny','Referenční seznam surovin.'],counts:['Inventury','Průběžná kontrola skutečného stavu.']}
const seed={materials:[{id:'S-001',name:'Hroznový extrakt',min:5000},{id:'S-002',name:'MagChel Magnesium bisglycinate',min:4000},{id:'S-003',name:'Heřmánkový extrakt',min:2500},{id:'S-004',name:'Mátový extrakt',min:2500},{id:'S-005',name:'Ashwagandha extrakt',min:3000}],boxes:Array.from({length:12},(_,i)=>({id:String(i+1)})),positions:Array.from({length:40},(_,i)=>({id:String.fromCharCode(65+i/10|0)+(i%10+1)})),packs:[{id:'P-2026-001',material:'S-001',lot:'AK-260801',expiry:'08/27',box:'1',position:'A1',qty:2400,packState:'nový'},{id:'P-2026-002',material:'S-001',lot:'AK-260812',expiry:'08/27',box:'2',position:'A2',qty:1800,packState:'otevřený'},{id:'P-2026-003',material:'S-002',lot:'MC-260802',expiry:'08/27',box:'3',position:'A3',qty:4100,packState:'nový'},{id:'P-2026-004',material:'S-003',lot:'HE-260805',expiry:'08/27',box:'4',position:'B1',qty:3200,packState:'nový'},{id:'P-2026-005',material:'S-004',lot:'ME-260808',expiry:'09/27',box:'5',position:'B2',qty:2100,packState:'otevřený'},{id:'P-2026-006',material:'S-005',lot:'AW-260810',expiry:'10/27',box:'6',position:'B3',qty:2900,packState:'nový'},{id:'P-2026-007',material:'S-002',lot:'MC-260818',expiry:'10/27',box:'7',position:'C1',qty:2200,packState:'nový'}],movements:[],counts:[],meta:{pack:8,movement:1,material:6,count:1}}
const state={page:'inventory',q:'',sort:{key:'material',dir:1},theme:localStorage.getItem(THEME_KEY)||'dark',compact:false}
let db=load()
const app=document.querySelector('#app')
app.innerHTML=`<div class="app-shell"><aside class="sidebar" id="sidebar"><div class="brand"><div class="brand-mark">M</div><div><b>MP12</b><span>INVENTORY</span></div></div><button class="new-btn" data-new>＋ Nový záznam</button><div class="nav-label">PAGES</div><nav id="nav"></nav><div class="sidebar-foot"><button class="ghost-btn" data-import>↑ Import CSV</button><button class="ghost-btn" data-export>↓ Export CSV</button><button class="ghost-btn" data-reset>↺ Obnovit data</button><button class="ghost-btn" data-theme>◐ Motiv</button><small>GitHub Pages · local DB</small></div></aside><main class="main"><header class="mobile-bar"><button id="menuBtn" class="icon-btn">☰</button><b>MP12</b></header><div id="stage" class="stage"></div></main></div><input id="csvFile" type="file" accept=".csv,text/csv" hidden><div id="modalRoot"></div><div id="toastRoot" class="toast-root"></div>`
function cp(x){return JSON.parse(JSON.stringify(x))}
function load(){try{const x=JSON.parse(localStorage.getItem(DB_KEY)||'null');return x?norm(x):cp(seed)}catch{return cp(seed)}}
function save(){localStorage.setItem(DB_KEY,JSON.stringify(db))}
function norm(x){const d={...cp(seed),...x};d.materials=Array.isArray(d.materials)?d.materials:cp(seed.materials);d.boxes=Array.isArray(d.boxes)?d.boxes.map(b=>({id:String(b.id).replace(/^B-/i,'')})):cp(seed.boxes);d.positions=Array.isArray(d.positions)?d.positions.map(p=>({id:String(p.id)})):cp(seed.positions);d.packs=Array.isArray(d.packs)?d.packs.map(p=>({...p,id:String(p.id),material:String(p.material),lot:String(p.lot||''),expiry:normExp(p.expiry),box:String(p.box||''),position:String(p.position||''),qty:Math.max(0,Number(p.qty)||0),packState:p.packState==='otevřený'?'otevřený':'nový'})):[];d.movements=Array.isArray(d.movements)?d.movements:[];d.counts=Array.isArray(d.counts)?d.counts:[];d.meta={...seed.meta,...(d.meta||{})};return d}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmt(v){return new Intl.NumberFormat('cs-CZ',{maximumFractionDigits:2}).format(Number(v)||0)}
function normExp(v){const m=String(v??'').trim().replace(/\./g,'/').match(/^(\d{1,2})\/(\d{2})$/);return m?`${m[1].padStart(2,'0')}/${m[2]}`:''}
function expRank(v){const m=String(v).match(/^(\d{2})\/(\d{2})$/);return m?(2000+Number(m[2]))*12+Number(m[1]):Infinity}
function expState(v){const r=expRank(v);if(!Number.isFinite(r))return'neznámá';const n=new Date(),cur=n.getFullYear()*12+n.getMonth()+1,d=r-cur;return d<0?'po expiraci':d<=2?'brzy expiruje':'OK'}
function mat(id){return db.materials.find(x=>x.id===id)}
function pack(id){return db.packs.find(x=>x.id===id)}
function active(){return db.packs.filter(p=>p.qty>0)}
function next(kind,prefix){const n=Number(db.meta[kind]||1);db.meta[kind]=n+1;return `${prefix}${String(n).padStart(3,'0')}`}
function date(v){return new Date(v).toLocaleString('cs-CZ',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}
function toast(s){const e=document.createElement('div');e.className='toast';e.textContent=s;document.querySelector('#toastRoot').append(e);setTimeout(()=>e.remove(),2200)}
function nav(){document.querySelector('#nav').innerHTML=Object.entries(PAGES).map(([id,p])=>`<button class="nav-item ${state.page===id?'active':''}" data-page="${id}"><span>•</span>${p[0]}</button>`).join('')}
function meta(){return PAGES[state.page]}
function shell(){const [title,desc]=meta();const l=document.createElement('section');l.className='page-layer current';l.innerHTML=`<div class="page-head"><div><div class="eyebrow">PAGES / ${state.page.toUpperCase()}</div><h1>${title}</h1><p>${desc}</p></div><div class="head-actions"><button class="btn" data-refresh>Obnovit</button><button class="btn primary" data-add>＋ Přidat</button></div></div><div class="page-content">${content()}</div>`;return l}
function mount(){const s=document.querySelector('#stage');s.innerHTML='';s.append(shell());nav();document.documentElement.dataset.theme=state.theme;document.body.classList.toggle('compact',state.compact)}
function go(page){if(page===state.page)return;const old=document.querySelector('.page-layer.current');state.page=page;state.q='';const next=shell();next.classList.add('enter');document.querySelector('#stage').append(next);requestAnimationFrame(()=>{next.classList.remove('enter');if(old){old.classList.add('exit');setTimeout(()=>old.remove(),250)}});nav();document.querySelector('#sidebar').classList.remove('open')}
function tools(extra=''){return`<div class="table-tools"><label class="search"><span>⌕</span><input data-search value="${esc(state.q)}" placeholder="Hledat…"></label><div class="tool-group">${extra}<button class="btn small" data-compact>${state.compact?'Standard':'Kompaktní'}</button></div></div>`}
function th(k,t){return`<th><button class="th-btn" data-sort="${k}">${t}<span>↕</span></button></th>`}
function inventory(){let a=active();const q=state.q.toLocaleLowerCase('cs-CZ');a=a.filter(p=>`${p.id} ${mat(p.material)?.name||''} ${p.lot} ${p.expiry} ${p.box} ${p.position} ${p.packState}`.toLocaleLowerCase('cs-CZ').includes(q));a.sort((x,y)=>{const val=p=>state.sort.key==='material'?(mat(p.material)?.name||''):state.sort.key==='qty'?p.qty:state.sort.key==='expiry'?expRank(p.expiry):String(p[state.sort.key]||'');const A=val(x),B=val(y);return(A>B?1:A<B?-1:0)*state.sort.dir});return`${tools('<button class="btn small" data-receive>＋ Příjem</button>')}<div class="table-card"><table><thead><tr>${th('id','ID pytle')}${th('material','Surovina')}${th('lot','Šarže')}${th('expiry','Expirace')}${th('box','Box')}${th('position','Pozice')}${th('qty','Hmotnost (g)')}<th>Stav</th><th></th></tr></thead><tbody>${a.length?a.map(p=>`<tr><td class="mono"><b>${p.id}</b></td><td>${esc(mat(p.material)?.name||p.material)}</td><td class="mono">${esc(p.lot)}</td><td class="mono ${expState(p.expiry)==='OK'?'':'expiry-warn'}">${p.expiry}</td><td class="mono">${p.box}</td><td><span class="chip">${p.position}</span></td><td class="mono"><b>${fmt(p.qty)}</b></td><td><span class="badge ${p.packState==='otevřený'?'open':'new'}">${p.packState}</span></td><td><div class="row-inline-actions"><button class="row-action" data-detail="${p.id}">Detail</button><button class="row-action" data-move="${p.id}">Přesun</button><button class="row-action" data-issue="${p.id}">Výdej</button></div></td></tr>`).join(''):`<tr><td class="empty" colspan="9">Žádné záznamy.</td></tr>`}</tbody></table></div>`}
function warehouse(){return`<div class="warehouse-card"><div class="warehouse-grid">${db.positions.map(pos=>{const a=active().filter(p=>p.position===pos.id),q=a.reduce((n,p)=>n+p.qty,0);return`<button class="slot ${a.length?'busy':''}" data-slot="${pos.id}"><b>${pos.id}</b><span>${a.length?`${a.length} pytle`:'volná'}</span>${a.length?`<small>${fmt(q)} g</small>`:''}</button>`}).join('')}</div></div>`}
function movements(){let a=db.movements.filter(m=>`${m.id} ${m.type} ${m.pack} ${m.from} ${m.to} ${m.reason}`.toLowerCase().includes(state.q.toLowerCase())).slice().reverse();return`${tools()}<div class="table-card"><table><thead><tr><th>ID</th><th>Čas</th><th>Typ</th><th>Pytel</th><th>Trasa</th><th>Množství</th><th>Důvod</th></tr></thead><tbody>${a.length?a.map(m=>`<tr><td class="mono">${m.id}</td><td>${date(m.date)}</td><td><span class="badge ${m.type==='Výdej'?'open':'new'}">${m.type}</span></td><td class="mono">${m.pack}</td><td>${m.from} → ${m.to}</td><td class="mono">${m.qty?`${m.qty>0?'+':''}${fmt(m.qty)} g`:'—'}</td><td>${esc(m.reason||'')}</td></tr>`).join(''):`<tr><td class="empty" colspan="7">Žádné pohyby.</td></tr>`}</tbody></table></div>`}
function materials(){const a=db.materials.filter(m=>`${m.id} ${m.name}`.toLowerCase().includes(state.q.toLowerCase()));return`${tools('<button class="btn small" data-material-new>＋ Surovina</button>')}<div class="table-card"><table><thead><tr><th>ID</th><th>Název</th><th>Minimum (g)</th><th>Zásoba</th><th></th></tr></thead><tbody>${a.map(m=>{const q=active().filter(p=>p.material===m.id).reduce((n,p)=>n+p.qty,0);return`<tr><td class="mono">${m.id}</td><td>${esc(m.name)}</td><td class="mono">${fmt(m.min)}</td><td class="mono">${fmt(q)} g</td><td><button class="row-action" data-material-edit="${m.id}">Upravit</button></td></tr>`}).join('')}</tbody></table></div>`}
function counts(){return`${tools('<button class="btn small" data-count-new>＋ Inventura</button>')}<div class="table-card"><table><thead><tr><th>ID</th><th>Vytvořeno</th><th>Položek</th><th>Stav</th></tr></thead><tbody>${db.counts.length?db.counts.slice().reverse().map(c=>`<tr><td class="mono">${c.id}</td><td>${date(c.createdAt)}</td><td>${c.items.length}</td><td><span class="badge">${c.status==='OPEN'?'Otevřená':'Uzavřená'}</span></td></tr>`).join(''):`<tr><td class="empty" colspan="4">Zatím žádná inventura.</td></tr>`}</tbody></table></div>`}
function content(){return state.page==='inventory'?inventory():state.page==='warehouse'?warehouse():state.page==='movements'?movements():state.page==='materials'?materials():counts()}
function modal(title,body,saveFn){const r=document.querySelector('#modalRoot');r.innerHTML=`<div class="modal-backdrop"><form class="modal-card" id="modal"><div class="modal-head"><div><div class="eyebrow">MP12</div><h2>${esc(title)}</h2></div><button type="button" class="icon-btn" data-close>×</button></div>${body}<div class="modal-actions"><button type="button" class="btn" data-close>Zrušit</button><button class="btn primary">Uložit</button></div></form></div>`;r.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>r.innerHTML='');r.querySelector('#modal').onsubmit=e=>{e.preventDefault();if(saveFn(new FormData(e.currentTarget))!==false)r.innerHTML=''}}
function receive(){modal('Příjem zásoby',`<div class="form-grid"><label>Surovina<select name="material">${db.materials.map(m=>`<option value="${m.id}">${esc(m.name)}</option>`).join('')}</select></label><label>Šarže<input name="lot" required></label><label>Expirace <small>mm/yy</small><input name="expiry" required pattern="\d{2}/\d{2}"></label><label>Hmotnost (g)<input name="qty" type="number" step="0.01" min="0.01" required></label><label>Box<select name="box">${db.boxes.map(b=>`<option>${b.id}</option>`).join('')}</select></label><label>Pozice<select name="position">${db.positions.map(p=>`<option>${p.id}</option>`).join('')}</select></label><label>Stav<select name="packState"><option>nový</option><option>otevřený</option></select></label></div>`,f=>{const expiry=normExp(f.get('expiry')),qty=Number(f.get('qty'));if(!/^\d{2}\/\d{2}$/.test(expiry)||qty<=0){toast('Neplatná expirace nebo hmotnost.');return false}const id=next('pack','P-2026-');const pos=String(f.get('position')),box=String(f.get('box'));db.packs.push({id,material:String(f.get('material')),lot:String(f.get('lot')).trim(),expiry,box,position:pos,qty,packState:String(f.get('packState'))});db.movements.push({id:next('movement','M-'),date:new Date().toISOString(),type:'Příjem',pack:id,qty,from:'Příjem',to:`${pos}/${box}`,reason:'Příjem zásoby'});save();mount();toast(`${id} přijat.`)})}
function issue(id){const p=pack(id);if(!p)return;modal(`Výdej · ${id}`,`<p class="modal-info">Na skladě: <b>${fmt(p.qty)} g</b></p><label>Množství (g)<input name="qty" type="number" min="0.01" max="${p.qty}" step="0.01" required></label><label>Důvod<input name="reason" value="Výdej"></label>`,f=>{const q=Number(f.get('qty'));if(!(q>0)||q>p.qty){toast('Neplatné množství.');return false}p.qty-=q;if(p.qty>0)p.packState='otevřený';db.movements.push({id:next('movement','M-'),date:new Date().toISOString(),type:'Výdej',pack:p.id,qty:-q,from:`${p.position}/${p.box}`,to:'Výdej',reason:String(f.get('reason')||'Výdej')});save();mount();toast(`Vydáno ${fmt(q)} g.`)})}
function move(id){const p=pack(id);if(!p)return;modal(`Přesun · ${id}`,`<label>Pozice<select name="position">${db.positions.map(x=>`<option ${x.id===p.position?'selected':''}>${x.id}</option>`).join('')}</select></label><label>Box<select name="box">${db.boxes.map(x=>`<option ${x.id===p.box?'selected':''}>${x.id}</option>`).join('')}</select></label><label>Důvod<input name="reason" value="Změna pozice"></label>`,f=>{const from=`${p.position}/${p.box}`;p.position=String(f.get('position'));p.box=String(f.get('box'));db.movements.push({id:next('movement','M-'),date:new Date().toISOString(),type:'Přesun',pack:p.id,qty:0,from,to:`${p.position}/${p.box}`,reason:String(f.get('reason')||'Přesun')});save();mount();toast(`${p.id} přesunut.`)})}
function detail(id){const p=pack(id);if(!p)return;modal(id,`<div class="detail-grid"><div><span>Surovina</span><b>${esc(mat(p.material)?.name||p.material)}</b></div><div><span>Šarže</span><b>${esc(p.lot)}</b></div><div><span>Expirace</span><b>${p.expiry}</b></div><div><span>Hmotnost</span><b>${fmt(p.qty)} g</b></div><div><span>Box</span><b>${p.box}</b></div><div><span>Pozice</span><b>${p.position}</b></div><div><span>Stav</span><b>${p.packState}</b></div><div><span>Expirace stav</span><b>${expiryState(p.expiry)}</b></div></div>`,()=>false)}
function materialModal(id=''){const m=id?mat(id):null;modal(m?'Upravit surovinu':'Nová surovina',`<label>Název<input name="name" required value="${esc(m?.name||'')}"></label><label>Minimum (g)<input name="min" type="number" min="0" step="0.01" value="${m?.min||0}"></label>`,f=>{const name=String(f.get('name')).trim();if(!name)return false;if(m)Object.assign(m,{name,min:Number(f.get('min'))||0});else db.materials.push({id:next('material','S-'),name,min:Number(f.get('min'))||0});save();mount();toast('Surovina uložena.')})}
function countNew(){const id=next('count','IC-');db.counts.push({id,createdAt:new Date().toISOString(),status:'OPEN',items:active().map(p=>({pack:p.id,system:p.qty,actual:null,position:p.position}))});save();mount();toast(`Inventura ${id} založena.`)}
function csvEsc(v){const s=String(v??'');return/[";,\n\r]/.test(s)?`"${s.replaceAll('"','""')}"`:s}
function exportCsv(){const lines=[CSV.join(';'),...db.packs.map(p=>CSV.map(k=>csvEsc(k==='material'?(mat(p.material)?.name||p.material):p[k])).join(';'))];const b=new Blob(['\uFEFF'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='mp12-sklad.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function parseCsv(t){const rs=[];let r=[],c='',q=false;const s=t.replace(/^\uFEFF/,'');for(let i=0;i<s.length;i++){const x=s[i],n=s[i+1];if(x==='"'&&q&&n==='"'){c+='"';i++;continue}if(x==='"'){q=!q;continue}if((x===';'||x===',')&&!q){r.push(c);c='';continue}if((x==='\n'||x==='\r')&&!q){if(x==='\r'&&n==='\n')i++;r.push(c);rs.push(r);r=[];c='';continue}c+=x}if(c||r.length){r.push(c);rs.push(r)}return rs.filter(x=>x.some(v=>v!==''))}
function importCsv(t){const rows=parseCsv(t);if(rows.length<2)return toast('CSV neobsahuje data.');const h=rows.shift().map(x=>x.trim());const idx=k=>h.indexOf(k),missing=CSV.filter(k=>idx(k)<0);if(missing.length)return toast(`CSV chybí: ${missing.join(', ')}`);const byId=new Map(db.materials.map(m=>[m.id,m.id])),byName=new Map(db.materials.map(m=>[m.name,m.id]));let added=0,updated=0,skip=0;for(const row of rows){const id=String(row[idx('id')]||'').trim(),mv=String(row[idx('material')]||'').trim(),expiry=normExp(row[idx('expiry')]),qty=Number(String(row[idx('qty')]||'').replace(',','.'));if(!id||!mv||!/^\d{2}\/\d{2}$/.test(expiry)||!(qty>0)){skip++;continue}let mid=byId.get(mv)||byName.get(mv);if(!mid){mid=next('material','S-');db.materials.push({id:mid,name:mv,min:0});byId.set(mid,mid);byName.set(mv,mid)}const item={id,material:mid,lot:String(row[idx('lot')]||'').trim(),expiry,box:String(row[idx('box')]||'').replace(/^B-/i,''),position:String(row[idx('position')]||'').trim(),qty,packState:String(row[idx('packState')]||'')==='otevřený'?'otevřený':'nový'};if(!item.box||!item.position){skip++;continue}const old=pack(id);if(old){Object.assign(old,item);updated++}else{db.packs.push(item);added++}if(!db.boxes.some(b=>b.id===item.box))db.boxes.push({id:item.box});if(!db.positions.some(p=>p.id===item.position))db.positions.push({id:item.position})}save();mount();toast(`CSV: ${added} nových, ${updated} upravených, ${skip} přeskočeno.`)}
function reset(){if(!confirm('Obnovit výchozí data?'))return;db=cp(seed);save();mount();toast('Data obnovena.')}

app.addEventListener('click',e=>{const pg=e.target.closest('[data-page]');if(pg)return go(pg.dataset.page);if(e.target.closest('[data-new]'))return state.page==='inventory'?receive():state.page==='materials'?materialModal():state.page==='counts'?countNew():toast('Na této stránce není nová položka.');if(e.target.closest('[data-import]'))return document.querySelector('#csvFile').click();if(e.target.closest('[data-export]'))return exportCsv();if(e.target.closest('[data-reset]'))return reset();if(e.target.closest('[data-theme]')){state.theme=state.theme==='dark'?'light':'dark';localStorage.setItem(THEME_KEY,state.theme);return mount()}if(e.target.closest('#menuBtn'))return document.querySelector('#sidebar').classList.toggle('open');if(e.target.closest('[data-refresh]'))return mount();if(e.target.closest('[data-add]'))return state.page==='inventory'?receive():state.page==='materials'?materialModal():state.page==='counts'?countNew():toast('Na této stránce není nová položka.');if(e.target.closest('[data-compact]')){state.compact=!state.compact;return mount()}const s=e.target.closest('[data-sort]');if(s){const k=s.dataset.sort;state.sort=state.sort.key===k?{key:k,dir:-state.sort.dir}:{key:k,dir:1};return mount()}if(e.target.closest('[data-receive]'))return receive();const d=e.target.closest('[data-detail]');if(d)return detail(d.dataset.detail);const m=e.target.closest('[data-move]');if(m)return move(m.dataset.move);const i=e.target.closest('[data-issue]');if(i)return issue(i.dataset.issue);const sl=e.target.closest('[data-slot]');if(sl){const p=active().find(x=>x.position===sl.dataset.slot);return p?detail(p.id):toast(`${sl.dataset.slot} je volná.`)}if(e.target.closest('[data-material-new]'))return materialModal();const me=e.target.closest('[data-material-edit]');if(me)return materialModal(me.dataset.materialEdit);if(e.target.closest('[data-count-new]'))return countNew()})
document.addEventListener('input',e=>{if(!e.target.matches('[data-search]'))return;state.q=e.target.value;const l=document.querySelector('.page-layer.current');if(!l)return;const top=l.scrollTop;l.querySelector('.page-content').innerHTML=content();l.scrollTop=top})
document.querySelector('#csvFile').addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>importCsv(String(r.result));r.readAsText(f,'utf-8');e.target.value=''})
mount()
